name: Build Simple Live App for Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 

      - name: Change to app directory
        run: cd simple_live_app

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: ./simple_live_app 

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./simple_live_app 

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk 
          path: simple_live_app/build/app/outputs/flutter-apk/app-release.apk 
